[package]
name = "protocol"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"

[dependencies]
serde.workspace = true
serde_with.workspace = true
serde_json.workspace = true
toml.workspace = true
thiserror.workspace = true
postcard.workspace = true
semver.workspace = true
